# Generated by Django 4.0 on 2022-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_interest_remove_profile_iterests_profile_iterests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='choice',
            new_name='name',
        ),
    ]
