# Generated by Django 4.0 on 2022-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_profile_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='interest',
            name='tr_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
