# Generated by Django 4.0 on 2022-12-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
