# Generated by Django 4.0 on 2022-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='base.Profile'),
        ),
    ]
