# Generated by Django 4.0 on 2022-11-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iterests',
            field=models.CharField(choices=[('Football', 'Football'), ('Voleyball', 'Voleyball'), ('Combat Sports', 'Combat Sports'), ('Podcasting', 'Podcasting'), ('Sports', 'Sports'), ('Celebrities', 'Celebrities'), ('Talk Shows', 'Talk Shows'), ('News', 'News'), ('Politis', 'Politics'), ('Turkey', 'Turkey'), ('USA', 'USA')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
